access_log logs/Twitter-access.log lite buffer=4k flush=5s if=$needlog;
error_log logs/Twitter-error.log;
proxy_next_upstream_tries 6;
proxy_next_upstream error timeout http_404 http_429 http_500 http_502 http_503 http_504;
include shared-proxy-params-1.conf;
proxy_ssl_name "";
proxy_ssl_session_reuse on;
proxy_ssl_protocols TLSv1.2 TLSv1.3;
