access_log logs/Twitter-access.log lite buffer=4k flush=5s if=$needlog;
error_log logs/Twitter-error.log;

proxy_connect_timeout 2;
proxy_next_upstream_tries 6;
proxy_next_upstream error timeout http_404 http_429 http_500 http_502 http_503 http_504;
proxy_ssl_session_reuse on;
proxy_ssl_protocols TLSv1.2 TLSv1.3;

grpc_connect_timeout 2;
grpc_next_upstream_tries 6;
grpc_next_upstream error timeout invalid_header http_404 http_429 http_500 http_502 http_503 http_504;
grpc_ssl_session_reuse on;
grpc_ssl_protocols TLSv1.2 TLSv1.3;