access_log logs/Twitter-access.log lite buffer=256;
error_log logs/Twitter-error.log;
proxy_next_upstream_tries 6;
proxy_next_upstream error timeout http_403 http_404 http_429 http_500 http_502 http_503 http_504 non_idempotent;
proxy_headers_hash_max_size 8192;
proxy_buffer_size 64k;
proxy_buffers 64 16k;
proxy_busy_buffers_size 256k;
proxy_set_header Connection "";
proxy_http_version 1.1;
proxy_set_header Host $http_host;
proxy_set_header User-Agent $http_user_agent;
proxy_max_temp_file_size 0;
proxy_buffering off;
proxy_ssl_server_name on;
proxy_ssl_name "";
proxy_ssl_session_reuse on;
proxy_ssl_protocols TLSv1.2 TLSv1.3;
