proxy_next_upstream error timeout http_429 http_404 http_500 http_502 http_503 http_504 non_idempotent;
proxy_hide_header Access-Control-Allow-Origin;
add_header Access-Control-Allow-Origin $http_origin always;
proxy_set_header Host $http_host;
proxy_set_header User-Agent $http_user_agent;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
add_header Server-Upstream $upstream_http_server;
add_header Backend-IP $upstream_addr;
proxy_connect_timeout 3;
proxy_read_timeout 3600s;
proxy_send_timeout 3600s;
proxy_http_version 1.1;
proxy_max_temp_file_size 0;
proxy_buffering off;
proxy_ssl_server_name on;