#   WallHaven Start
upstream WallHaven-cc {
	zone wallhaven-cc 64k;
	hash $connection consistent;
	server [2606:4700:20::ac43:416f]:443;
	server [2606:4700:100::ac43:4a6f]:443;
	server 104.17.176.9:443;
	server 172.64.144.19:443;
	keepalive 16;
	keepalive_timeout 300s;
}
upstream WallHaven-cc-LB {
	zone wallhaven-cc 64k;	
	least_conn;
	server [2606:4700:20::ac43:416f]:443;
	server [2606:4700:100::ac43:4a6f]:443;
	server 104.17.176.9:443;
	server 172.64.144.19:443;
	keepalive 16;
	keepalive_timeout 300s;
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;
	http2 on;
	server_name wallhaven.cc www.wallhaven.cc static.wallhaven.cc alpha.wallhaven.cc;

	client_max_body_size 50M;
	http2_max_concurrent_streams 8;

	location / {
		proxy_pass https://WallHaven-cc;
		proxy_next_upstream error timeout http_403 http_404 http_429 http_500 http_502 http_503 http_504;
		include shared-proxy-params-snidot.conf;
	}
}
server {
	listen 443 ssl;
	listen [::]:443 ssl;
	http2 on;
	server_name w.wallhaven.cc th.wallhaven.cc;

	client_max_body_size 50M;
	http2_max_concurrent_streams 8;

	location / {
		proxy_pass https://WallHaven-cc-LB;
		proxy_next_upstream error timeout http_403 http_404 http_429 http_500 http_502 http_503 http_504;
		include shared-proxy-params-snidot.conf;
	}
}
#   WallHaven End