#   GreasyFork Start
upstream GreasyFork-org {
	zone GreasyFork-org 64k;
	hash $connection consistent;
	server [2600:3c01::f03c:95ff:fe58:20d3]:443;
	server [2600:3c01::f03c:95ff:fee3:1156]:443;
	server 96.126.98.220:443;
	server 50.116.4.196:443;
	keepalive 16;
	keepalive_timeout 300s;
}
server {
	listen 443 ssl;
	listen [::]:443 ssl;
	http2 on;
	server_name api.GreasyFork.org;
	server_name update.GreasyFork.org;
	error_log nul;
	location / {
		proxy_pass https://GreasyFork-org;
		include shared-proxy-params-empty-sni.conf;
	}
}
server {
	listen 443 ssl;
	listen [::]:443 ssl;
	http2 on;
	server_name GreasyFork.org www.GreasyFork.org;
	error_log nul;
	location / {
		grpc_pass grpcs://Cloudflare;
		include shared-proxy-params-snidot.conf;
	}
}
#	GreasyFork-org End