#   archiveofourown Start
upstream archiveofourown.org {
	zone archiveofourown.org 64k;
	hash $connection consistent;
	server 104.20.9.2:443;
	server 104.20.8.2:443;
	server [2606:4700:57::6814:802]:443;
	server [2606:4700:3111::6814:802]:443;
	server [2606:4700:8ca2::6814:802]:443;
	server [2606:4700:839b::6814:802]:443;
	server [2606:4700:90d0::6814:802]:443;
	server [2606:4700:9a60::6814:802]:443;
	server [2606:4700:9aea::6814:802]:443;
	keepalive 16;
	keepalive_timeout 300s;
}
server {
	listen 443 ssl;
	listen [::]:443 ssl;
	http2 on;
	server_name .archiveofourown.org;

	location / {
		grpc_pass grpcs://archiveofourown.org;
		include shared-proxy-params-empty-sni.conf;
	}
}
#   archiveofourown End