log_format  Google  '［$time_local］－	请求耗时"$request_time"	$http_host	服务器地址：	$proxy_host	$server_protocol\n	上游状态	"$upstream_status"	上游地址：	"$upstream_addr"	$upstream_http_server\n	$status	总字节数$body_bytes_sent';

#　　GoogleVideo.com
split_clients $connection $domain_SUFFIX {
	20%   "gvt1.com";
	26%   "xn--ngstr-lra8j.com";
	20%   "bdn.dev";
	4%   "c.2mdn.net";
	4%   "snap.gvt1.com";
#	3%   "gcpcdn.gvt1.com";
	4%   "offline-maps.gvt1.com";
#	20%   "c.bigcache.googleapis.com";
	22%   "c.googlesyndication.com";
}
server {
	listen 443 ssl;
	listen [::]:443 ssl;
	http2 on;
	server_name ~^(?<prefix_name>.+)\.googlevideo\.com$;
	server_name ~^(?<prefix_name>.+)\.c\.youtube\.com$;

	access_log off;
	#access_log logs/GoogleVideo-access.log Google buffer=4k flush=5s if=$needlog;
	error_log NUL;

	location / {
		proxy_max_temp_file_size 0;
		resolver 119.29.29.29:53 valid=1h ipv4=off ipv6=on;
		proxy_pass https://$prefix_name.${domain_SUFFIX}:443;
		proxy_ssl_name $proxy_host;
		proxy_set_header Range $http_range;
		proxy_set_header If-Range $http_if_range;
		proxy_connect_timeout 5;
		proxy_set_header Connection "";
		proxy_http_version 1.1;
		proxy_set_header Host $http_host;
		proxy_set_header User-Agent $http_user_agent;
		proxy_buffering off;
		proxy_ssl_server_name on;
		proxy_ssl_session_reuse on;

		keepalive_timeout 600;
		keepalive_requests 100000;
	}
}
#	GoogleVideo End