#   Wiki Start
upstream wikipedia-text-lb {
	zone wikipedia-text-lb 64k;
	hash $connection consistent;
	server 208.80.153.224:443;
	server 195.200.68.224:443;
	server 185.15.58.224:443;
	server 185.15.59.224:443;
	server 103.102.166.225:443;
	server [2620:0:863:ed1a::1]:443;
	server [2620:0:861:ed1a::1]:443;
	server [2620:0:860:ed1a::1]:443;
	server [2a02:ec80:700:ed1a::1]:443;#High-Ping,backup
	server [2a02:ec80:600:ed1a::1]:443;
	server [2a02:ec80:300:ed1a::1]:443;
	server [2001:df2:e500:ed1a::1]:443;
	keepalive 32;
	keepalive_time 1h;
	keepalive_timeout 120;
	keepalive_requests 10000;
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;
	http2 on;
	server_name .wikipedia.org;
	server_name .m.wikipedia.org;
	server_name .wikimedia.org;
	server_name .m.wikimedia.org;

	location / {
		proxy_pass https://wikipedia-text-lb;
		include shared-proxy-params-empty-sni.conf;
		proxy_next_upstream error timeout http_429 http_500 http_502 http_503 http_504 non_idempotent;
	}
}

upstream wikipedia-upload-lb {
	zone wikipedia-upload-lb 64k;
	hash $connection consistent;
	server 185.15.58.240:443;
	server 185.15.59.240:443;
	server 195.200.68.240:443;
	server 208.80.153.240:443;
	server 208.80.154.240:443;
	server [2620:0:863:ed1a::2:b]:443;
	server [2620:0:861:ed1a::2:b]:443;
	server [2620:0:860:ed1a::2:b]:443;
	server [2a02:ec80:700:ed1a::2:b]:443;#High-Ping,backup
	server [2a02:ec80:600:ed1a::2:b]:443;
	server [2a02:ec80:300:ed1a::2:b]:443;
	server [2001:df2:e500:ed1a::2:b]:443;
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;
	http2 on;
	server_name upload.wikimedia.org;

	location / {
		proxy_pass https://wikipedia-upload-lb;
		proxy_connect_timeout 15;
		include shared-proxy-params-empty-sni.conf;
	}
}
#   Wiki End