#   gumroad Start
#upstream gumroad-disable {
#	server 52.207.15.53:443;
#	server 18.204.61.141:443;
#	server 34.225.249.131:443;
#	server 34.198.86.74:443;
#	server 34.233.172.68:443;
#	server 35.170.108.33:443;
#}
upstream gumroad {
	hash $connection consistent;
	server 104.17.176.98:443;
	server [2606:4700:100::6811:b062]:443;
	server [2606:4700::6812:f363]:443;
	keepalive 16;
	keepalive_time 1h;
	keepalive_timeout 300s;
	keepalive_requests 10000;
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;
	http2 on;
	server_name gumroad.com;
	server_name *.gumroad.com;

	client_max_body_size 50M;

	location / {
		set $gumroad_sni "gum,road.com";
		if ($host ~* ^(.*)gumroad\.com$) {
			set $gumroad_sni "$1gum,road.com";
		}
		proxy_pass https://gumroad;
		proxy_buffer_size  64k;
		proxy_buffers   32 64k;
		proxy_busy_buffers_size 128k;
		proxy_ssl_name $gumroad_sni;
		include shared-proxy-params-1.conf;
	}
}
#   gumroad End