#   dlsite Start
upstream dlsite-login {
	server 52.195.112.119:443;
	server 18.179.135.142:443;
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;
	server_name download.dlsite.com media.dlsite.com;

	location / {
		proxy_pass https://CloudFront;
		include shared-proxy-params-empty-sni.conf;
	}
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;
	server_name login.dlsite.com;

	location / {
		#proxy_pass https://dlsite-login;
	resolver 9.9.9.9:9953 valid=3600s ipv4=on ipv6=on;
	set $rewrite_host "login.dlsite.com.";
		proxy_pass https://$rewrite_host;
		include shared-proxy-params-empty-sni.conf;
	}
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;
	server_name www.dlsite.com ssl.dlsite.com img.dlsite.jp media.ci-en.jp;

	location / {
		grpc_pass grpcs://CloudFlare;
		include shared-proxy-params-snidot.conf;
	}
}
#   dlsite End